name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-pip && python3 -m pip install -r requirements.txt
      - run: python3 -m black --diff --check $(git ls-files '*.py')
      - run: python3 -m pylint --disable=all --enable=unused-import --ignore-patterns=compile.py $(git ls-files '*.py')
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-pip && python3 -m pip install -r build_requirements.txt && python3 -m spacy download 'en_core_web_lg'
      - name: test
        run: |
          python3 -m unittest discover tests/
